# This is project specific rubocop configuration file.
# You can tweak project settings here
inherit_from:
  - ./.rubocop.localch.yml

AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'Gemfile'

Metrics/BlockLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
